name: '12345'
favicon: null
layout_spectrum: 0.6140564132947475
typography_spectrum: 0.396102488739416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6308215807657689
  lightness: 0.4914685278199613
  saturation: 0.9359834629576653
  rhythmicContrast: 0.5118648938369006
purpose: []
